# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Auret\MatchedBetting\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Auret\BetProfiler\Boundary\ExchangeBoundaryInterface:
        class: Auret\BetProfiler\Interactor\ExchangeInteractor

    Auret\BetProfiler\Boundary\BookmakerBoundaryInterface:
        class: Auret\BetProfiler\Interactor\BookmakerInteractor

    Auret\BetProfiler\Boundary\EventTypeBoundaryInterface:
        class: Auret\BetProfiler\Interactor\EventTypeInteractor

    Auret\BetProfiler\Boundary\MarketTypeBoundaryInterface:
        class: Auret\BetProfiler\Interactor\MarketTypeInteractor

    Auret\BetProfiler\Boundary\MatchedBetBoundaryInterface:
        class: Auret\BetProfiler\Interactor\MatchedBetInteractor

    Auret\BetProfiler\Controller\BackBetController:
        class: Auret\BetProfiler\Controller\BackBetController

    Auret\BetProfiler\Controller\LayBetController:
        class: Auret\BetProfiler\Controller\LayBetController

    Auret\BetProfiler\Controller\EventController:
        class: Auret\BetProfiler\Controller\EventController

    Auret\BetProfiler\Gateway\ExchangeGatewayInterface: '@Auret\MatchedBetting\Repository\ExchangeRepository'
    Auret\BetProfiler\Gateway\BookmakerGatewayInterface: '@Auret\MatchedBetting\Repository\BookmakerRepository'
    Auret\BetProfiler\Gateway\EventTypeGatewayInterface: '@Auret\MatchedBetting\Repository\EventTypeRepository'
    Auret\BetProfiler\Gateway\MarketTypeGatewayInterface: '@Auret\MatchedBetting\Repository\MarketTypeRepository'
    Auret\BetProfiler\Gateway\BackBetGatewayInterface: '@Auret\MatchedBetting\Repository\BackBetRepository'
    Auret\BetProfiler\Gateway\LayBetGatewayInterface: '@Auret\MatchedBetting\Repository\LayBetRepository'
    Auret\BetProfiler\Gateway\EventGatewayInterface: '@Auret\MatchedBetting\Repository\EventRepository'
    Auret\BetProfiler\Gateway\MatchedBetGatewayInterface: '@Auret\MatchedBetting\Repository\MatchedBetRepository'
